steps:
# Setup Env
- id: 'setup-environment'
  name: python
  entrypoint: bash
  args: ['-c', 'pip install -U dvc dvc[gs]; dvc pull;']

# Build & Push Trainer
- name: 'gcr.io/cloud-builders/docker'
  id: 'Build container image'
  args: [
    'build',
    '.',
    '-t',
    'europe-west3-docker.pkg.dev/$PROJECT_ID/group28-repository/app:latest',
    '-f',
    'dockerfiles/api.dockerfile'
  ]
- name: 'gcr.io/cloud-builders/docker'
  id: 'Push container image'
  args: [
    'push',
    'europe-west3-docker.pkg.dev/$PROJECT_ID/group28-repository/app:latest'
  ]
options:
  logging: CLOUD_LOGGING_ONLY
