steps:
# Setup Env
- id: 'setup-environment'
  name: python
  entrypoint: bash
  args: ['-c', 'pip install -U dvc dvc[gs]; dvc pull;']

# Build & Push Trainer
- name: 'gcr.io/cloud-builders/docker'
  id: 'Build container image'
  args: [
    'build',
    '.',
    '-t',
    'europe-west3-docker.pkg.dev/$PROJECT_ID/group28-repository/app:latest',
    '-f',
    'dockerfiles/api.dockerfile'
  ]

- name: 'gcr.io/cloud-builders/docker'
  id: 'Push container image'
  args: [
    'push',
    'europe-west3-docker.pkg.dev/$PROJECT_ID/group28-repository/app:latest'
  ]

# Deploy to Cloud Run with Secret Access
- name: 'gcr.io/cloud-builders/gcloud'
  id: 'Deploy to Cloud Run'
  args: [
    'run',
    'deploy',
    'app-docker-image',
    '--image',
    'europe-west3-docker.pkg.dev/$PROJECT_ID/group28-repository/app:latest',
    '--region',
    'europe-west1',
    '--platform',
    'managed',
    '--port',
    '8000',
    '--memory',
    '16Gi',
    '--cpu',
    '4',
    '--allow-unauthenticated',
    '--set-secrets',
    'WANDB_API_KEY=projects/294894715547/secrets/WANDB_API_KEY_NANDOR:latest'
  ]

# Ensure Cloud Run Allows Unauthenticated Access
- name: 'gcr.io/cloud-builders/gcloud'
  id: 'Allow Unauthenticated Access'
  waitFor: ['Deploy to Cloud Run']  # Ensures this runs after deployment
  args: [
    'run',
    'services',
    'add-iam-policy-binding',
    'app-docker-image',
    '--region',
    'europe-west1',
    '--member=allUsers',
    '--role=roles/run.invoker'
  ]

options:
  logging: CLOUD_LOGGING_ONLY
