# config_cpu.yaml
workerPoolSpecs:
  machineSpec:
    machineType: n1-highmem-2
  replicaCount: 1
  containerSpec:
    imageUri: europe-west3-docker.pkg.dev/mlops-group28/group28-repository/train-docker-image:latest
