name: Code formatting

on:
  push:
    branches:
      - master
      - main

  pull_request:
    branches:
      - master
      - main

jobs:
  codecheck:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11
          cache: 'pip'
          cache-dependency-path: setup.py

      - name: Install dependencies
        run: |
          pip install ruff==0.8.6
          pip list

      - name: Ruff check
        run: ruff check .

      - name: Ruff format
        run: ruff format .